name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - run: nix build .#
    - run: ./result
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "result"
        body: "Automated Build"
