name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/build.yml
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "./result"
        body: "Automated build"
